### ISSUE TITLE
No URLs show after Jamf Pro 10.30.x update

### ISSUE THREAD

**Issue by macmule** [dataJAR/Jamf-Switcher#9]
<img width="678" alt="Screenshot 2021-06-19 at 09 29 27" src="https://user-images.githubusercontent.com/2464974/122636374-dd5c5680-d0e0-11eb-91eb-15e46755ace5.png">

**Comment by macmule** [comment]
New location for the file with the bookmarks - `/Library/Application Support/JAMF/Composer/Sources/bookmarks/ROOT/Users/ben/Library/Application Support/com.jamfsoftware.selfservice.mac/CocoaAppCD.storedata`

Data format - 
```
    <object type="SSBOOKMARK" id="z2603">
        <attribute name="url" type="string">https://some/url</attribute>
        <attribute name="priority" type="int64">5</attribute>
        <attribute name="displayinbrowser" type="bool">0</attribute>
        <attribute name="name" type="string">Somename</attribute>
        <attribute name="jssdescription" type="string">JSS</attribute>
        <attribute name="installstatus" type="int64">0</attribute>
        <attribute name="id" type="int64">41</attribute>
        <attribute name="iconurl" type="string">https://some/url/iconservlet/?id=104</attribute>
        <attribute name="compliance" type="bool">0</attribute>
        <attribute name="buttontext" type="string">Open</attribute>
    </object>

```

**Comment by red5coder** [comment]
Have updated the app to look for both the old location and new. Due to sandboxing, on first launch the app will ask you to grant permissions to the new location. It should then save that permission. Currently in testing.

**Comment by red5coder** [comment]
This seems to be working so will close this issue. Changes have been added to 1.3

**Comment by red5coder** [comment]
Have had to remove the sandboxing. With it active could not set Jamf Admins preferences.

**Comment by red5coder** [comment]
Sandboxing has been removed
